version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  time:
    build: .
    ports:
      - "3002:3000"
      - "24678:24678" # dev live-reload ws
    links:
      - "mongo:db"
    volumes:
      - type: bind
        source: ./
        target: /tmp/time
volumes:
  grafana:
  mongo:
